name: updating website

run-name: ${{ github.actor }} is updating the website
on: [workflow_dispatch]
jobs:
  update-s3-website:
    runs-on: ubuntu-latest
    steps:

      - name: Install pdftk
        uses: actions/checkout@v3
      - run: |
          sudo apt update -y
          sudo wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pdftk/pdftk_2.02-5_amd64.deb
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}  
          role-duration-seconds: 1200
          role-session-name: MySessionName        
      - run: |
          ls -la
#######          aws s3 sync s3://halab.info 

#######